### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by nikhilwoodruff**

### CODE REVIEW

**Comment by nikhilwoodruff** [comment]
Nearly there- includes much more granular SPI statistics and documentation for the full process.

Currently investigating why we don't seem to be calibrating right for the 1m+ total income targets.

**Comment by nikhilwoodruff** [comment]
Update: looks really good in targeting! The only final blocker that needs some investigation is Income Tax being on an increasing-underestimate path compared to official forecasts. It looks like it's employment income driven. 

image

**Comment by MaxGhenis** [comment]
What was the issue with the high income and pension groups?

**Comment by nikhilwoodruff** [comment]
Added more detail in #5 - merging.

**Pull request merged**
